services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DATA: /var/lib/postgres/data
      POSTGRES_DB: book_app
    volumes:
      - postgres: /data/postgres
    ports:
      - 5432:5432
    networks:
      - book-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-book
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres:
    driver: local
networks:
  book-network:
    driver: bridge