spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 3000
        timeout: 3000
        writetimeout: 4000
    username: razvan@yahoo.com
    password: password
    activation-url: http:/localhost:4200/activation-url
jwt:
  secret-key: b582b92445bd2be1fd47e16d3d055e7e1d194813a0f64a0769fdf4314f0fd739f05553e3812f8a0e2d1822bf
  expiration: 1800000

